version: 2
updates:
  - package-ecosystem: composer
    directory: /server
    schedule:
      interval: monthly
    groups:
      minor-and-patch:
        update-types:
          - minor
          - patch
    commit-message:
      prefix: "chore(deps)"
    labels:
      - dependencies

  - package-ecosystem: npm
    directory: /server
    schedule:
      interval: monthly
    groups:
      minor-and-patch:
        update-types:
          - minor
          - patch
    commit-message:
      prefix: "chore(deps)"
    labels:
      - dependencies

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      minor-and-patch:
        update-types:
          - minor
          - patch
    commit-message:
      prefix: "chore(deps)"
    labels:
      - dependencies
