<?php

namespace Tests\Feature;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\Feature\Concerns\FixtureLexiconTestHelpers;
use Tests\TestCase;

/**
 * The DataTables endpoint behind the public "Data" page. The fixture lexicon's
 * data cache is generated by the seeder, so rows exist for en, es and te.
 */
class LexiconDataEndpointTest extends TestCase
{
    use FixtureLexiconTestHelpers;
    use RefreshDatabase;

    private const URL = '/api/v1/lexicon/fixturelex/data';

    protected function setUp(): void
    {
        parent::setUp();

        $this->seedFixtureLexicon();
    }

    public function test_defaults_apply_when_no_parameters_are_sent(): void
    {
        $response = $this->getJson(self::URL)
            ->assertOk()
            ->assertJsonStructure(['draw', 'recordsTotal', 'recordsFiltered', 'data']);

        $this->assertGreaterThan(0, $response->json('recordsTotal'));
        $this->assertSame($response->json('recordsTotal'), $response->json('recordsFiltered'));
        $this->assertLessThanOrEqual(10, count($response->json('data')));
    }

    public function test_global_search_filters_rows_by_any_column(): void
    {
        $response = $this->getJson(self::URL.'?'.http_build_query([
            'search' => ['value' => 'father', 'regex' => 'false'],
            'length' => 100,
        ]))->assertOk();

        $this->assertGreaterThan(0, $response->json('recordsFiltered'));
        $this->assertLessThan($response->json('recordsTotal'), $response->json('recordsFiltered'));
        foreach ($response->json('data') as $row) {
            $this->assertStringContainsStringIgnoringCase('father', json_encode($row));
        }
    }

    public function test_plain_search_treats_regex_metacharacters_literally(): void
    {
        $this->getJson(self::URL.'?'.http_build_query([
            'search' => ['value' => '(', 'regex' => 'false'],
        ]))->assertOk()->assertJsonPath('recordsFiltered', fn ($n) => is_int($n));
    }

    public function test_malformed_regular_expression_is_a_client_error_not_a_crash(): void
    {
        $this->getJson(self::URL.'?'.http_build_query([
            'search' => ['value' => '(', 'regex' => 'true'],
        ]))->assertStatus(422)->assertJsonStructure(['draw', 'error']);
    }

    public function test_unknown_column_is_rejected(): void
    {
        $this->getJson(self::URL.'?'.http_build_query([
            'columns' => [['name' => 'not_a_column', 'search' => ['value' => 'x', 'regex' => 'false']]],
        ]))->assertStatus(422)->assertJsonStructure(['draw', 'error']);
    }

    public function test_unknown_order_column_and_bad_direction_are_rejected(): void
    {
        $this->getJson(self::URL.'?'.http_build_query([
            'order' => [['name' => 'not_a_column', 'dir' => 'asc']],
        ]))->assertStatus(422);

        $this->getJson(self::URL.'?'.http_build_query([
            'order' => [['name' => 'meaning', 'dir' => 'sideways']],
        ]))->assertStatus(422);
    }

    public function test_page_length_is_capped(): void
    {
        $this->getJson(self::URL.'?length=1000')->assertStatus(422);
        $this->getJson(self::URL.'?length=100')->assertOk();
    }

    public function test_ordering_by_a_data_column_works(): void
    {
        $asc = $this->getJson(self::URL.'?'.http_build_query([
            'order' => [['name' => 'meaning', 'dir' => 'asc']], 'length' => 100,
        ]))->assertOk()->json('data');
        $desc = $this->getJson(self::URL.'?'.http_build_query([
            'order' => [['name' => 'meaning', 'dir' => 'desc']], 'length' => 100,
        ]))->assertOk()->json('data');

        // Rows with equal meanings may come back in any order, so compare the
        // sequence of distinct values rather than row ids.
        $distinct = fn (array $rows) => array_values(array_unique(array_column($rows, 'meaning')));
        $this->assertNotEmpty($distinct($asc));
        $this->assertSame($distinct($asc), array_reverse($distinct($desc)));
    }
}
